version: "3.01"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=clubs_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
        # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
        # Opens port 3306 on the container
      - '3306'


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80

  api:
    build: ./api
    container_name: api
    restart: always
    volumes: ['./api/:/app']
    ports: ['9000:9000']

  vue-app:
    build: ./vue-app
    container_name: vue-app
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"